### ISSUE TITLE
NameError: name 'nn_shutdown' is not defined

### ISSUE THREAD

**Issue by danielnelson** [tonysimpson/nanomsg-python#42]
I get an error when calling shutdown on an endpoint:
```
$ cat tmp.py 
import nanomsg

socket = nanomsg.Socket(nanomsg.PAIR)
endpoint = socket.bind('inproc://foo')
endpoint.shutdown()
$ python tmp.py 
Traceback (most recent call last):
  File "tmp.py", line 5, in <module>
    endpoint.shutdown()
  File "/home/dbn/usr/lib/python3.4/site-packages/nanomsg/__init__.py", line 140, in shutdown
    _nn_check_positive_rtn(nn_shutdown(self._fdocket._s,
NameError: name 'nn_shutdown' is not defined
```

**Comment by jb098** [comment]
I've submitted a pull request that should hopefully resolve this.

**Comment by tonysimpson** [comment]
This has been merged, thanks.
